---
- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  loop: "{{ users_to_create }}"
  when: users_to_create | length > 0

- name: Modify users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: present
  loop: "{{ users_to_modify }}"
  when: users_to_modify | length > 0

- name: Remove users
  user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ users_to_remove }}"
  when: users_to_remove | length > 0
