---
- name: Converge
  hosts: all
  become: true
  vars:
    users_to_create:
      - name: testuser1
        shell: "/bin/bash"
      - name: testuser2
        shell: "/bin/bash"
    users_to_modify:
      - name: testuser4
        shell: "/bin/sh"
    users_to_remove:
      - testuser3

  roles:
    - role: ansible_user_management
